quarkus:
  banner:
    enabled: true
    path: banner.txt

keeper:
  parallelism: ${KEEPER_SERVICE_PARALLELISM:4}
  database-path: ${KEEPER_DATABASE_PATH}
  session:
    gg20:
      expire: 15m
    frost:
      expire: 5m